name: kjv_strong
description: KJV with Strong's Concordance


version: 2.0.0+4

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_riverpod: ^1.0.4
  google_fonts: ^3.0.1
  get_storage: ^2.0.3
  url_launcher: ^6.1.5
  share: ^2.0.4
  animations: ^2.0.4
  scrollable_positioned_list: ^0.3.4
  selectable: ^0.2.4
  flutter_html: ^2.2.1
  sqflite: ^2.0.3+1
  path: ^1.8.2
  facebook_audience_network: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
#  flutter_native_splash: ^1.3.3
#  flutter_launcher_icons: ^0.9.2

#flutter_native_splash:
#    color: "#ffffff"
#    image: "assets/images/icon.png"
#    color_dark: "0f0101"
#    android: true
#    ios: false

#flutter_icons:
#  android: true
#  ios: false
#  image_path: "assets/images/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/sqlite/
  #  flutter pub run flutter_launcher_icons:main
#  flutter pub run flutter_native_splash:create